import { useAuth } from '../context/AuthContext';
import { Hash, Sparkles, Download } from 'lucide-react'
import React, { useState } from 'react'
import toast from 'react-hot-toast'
import Markdown from 'react-markdown'
import axios from '../utils/axios'
import { jsPDF } from 'jspdf'

const BlogTitles = () => {

  const blogCategories = ['General',  'Technology', 'Business', 'Health', 'Lifestyle', 'Education', 'Travel', 'Food']
  
    const [selectedCategory, setSelectedCategory] = useState('General')
    const [input, setInput] = useState('')

    const [loading, setLoading] = useState(false)
    const [content, setContent] = useState('')

    const { token } = useAuth()
  
    const handleDownloadPDF = () => {
      try {
        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.getWidth();
        const pageHeight = doc.internal.pageSize.getHeight();
        const margin = 20;
        const maxWidth = pageWidth - 2 * margin;
        
        // Remove markdown formatting for cleaner PDF
        let cleanText = content
          .replace(/#{1,6}\s/g, '') // Remove headers
          .replace(/\*\*(.+?)\*\*/g, '$1') // Remove bold
          .replace(/\*(.+?)\*/g, '$1') // Remove italic
          .replace(/\[(.+?)\]\(.+?\)/g, '$1') // Remove links
          .replace(/`(.+?)`/g, '$1'); // Remove code blocks
        
        // Add title
        doc.setFontSize(18);
        doc.setFont(undefined, 'bold');
        doc.text('Generated Blog Titles', margin, margin);
        
        // Add metadata
        doc.setFontSize(10);
        doc.setFont(undefined, 'normal');
        doc.text(`Keyword: ${input}`, margin, margin + 10);
        doc.text(`Category: ${selectedCategory}`, margin, margin + 16);
        const date = new Date().toLocaleDateString();
        doc.text(`Generated on: ${date}`, margin, margin + 22);
        
        // Add content
        doc.setFontSize(12);
        const lines = doc.splitTextToSize(cleanText, maxWidth);
        let y = margin + 35;
        
        lines.forEach((line) => {
          if (y > pageHeight - margin) {
            doc.addPage();
            y = margin;
          }
          doc.text(line, margin, y);
          y += 8;
        });
        
        // Add footer
        doc.setFontSize(9);
        doc.setTextColor(128);
        doc.text(
          'Generated by Aivora AI',
          pageWidth / 2,
          pageHeight - 10,
          { align: 'center' }
        );
        
        doc.save(`aivora-blog-titles-${Date.now()}.pdf`);
        toast.success('Blog titles downloaded as PDF!');
      } catch (error) {
        console.error('PDF generation error:', error);
        toast.error('Failed to generate PDF');
      }
    };

    const onSubmitHandler = async (e)=>{
      e.preventDefault();
      try {
         setLoading(true)
         const prompt = `Generate a blog title for the keyword ${input} in the category ${selectedCategory}`

         const { data } = await axios.post('/api/ai/generate-blog-title', {prompt}, {headers: {Authorization: `Bearer ${token}`}})

         if (data.success) {
          setContent(data.content)
         }else{
          toast.error(data.message)
         }
      } catch (error) {
        toast.error(error.message)
      }
      setLoading(false)
    }

  return (
    <div className='h-full overflow-y-scroll p-6 text-slate-700'>
      <div className='max-w-7xl mx-auto grid grid-cols-1 lg:grid-cols-2 gap-6'>
        {/* left col */}
        <form onSubmit={onSubmitHandler} className='bg-white rounded-xl border border-gray-200 p-6 shadow-md h-fit'>
          <div className='flex items-center gap-3'>
            <Sparkles className='w-6 text-[#8E37EB]'/>
            <h1 className='text-xl font-semibold'>AI Title Generator</h1>
          </div>
          <p className='mt-6 text-sm font-medium'>Keyword</p>

          <input onChange={(e)=>setInput(e.target.value)} value={input} type="text" className='w-full p-2 px-3 mt-2 outline-none text-sm rounded-md border border-gray-300' placeholder='The future of artificial intelligence is...' required/>

          <p className='mt-4 text-sm font-medium'>Category</p>

          <div className='mt-3 flex gap-3 flex-wrap sm:max-w-9/11'>
            {blogCategories.map((item)=>(
              <span onClick={()=> setSelectedCategory(item)} 
              className={`text-xs px-4 py-1 border rounded-full cursor-pointer ${selectedCategory === item ? 'bg-purple-50 text-purple-700' : 'text-gray-500 border-gray-300'}`} key={item}>{item}</span>
            ) )}
          </div>
          <br/>
          <button disabled={loading} className='w-full flex justify-center items-center gap-2 bg-gradient-to-r from-[#C341F6] to-[#8E37EB] text-white px-4 py-2 mt-6 text-sm rounded-lg cursor-pointer hover:from-[#B030E5] hover:to-[#7D26DA] transition-all shadow-md hover:shadow-lg'>
            {loading ? <span className='w-4 h-4 my-1 rounded-full border-2 border-t-transparent animate-spin'></span> : <Hash className='w-5'/>}
            Generate title
          </button>
        </form>
        
        {/* Right col */}
        <div className='bg-white rounded-xl border border-gray-200 p-6 shadow-md flex flex-col min-h-[600px]'>

            <div className='flex items-center justify-between'>
              <div className='flex items-center gap-3'>
                <Hash className='w-5 h-5 text-[#8E37EB]' />
                <h1 className='text-xl font-semibold'>Generated titles</h1>
              </div>
              {content && (
                <button
                  onClick={handleDownloadPDF}
                  className='flex items-center gap-2 px-4 py-2 bg-gradient-to-r from-purple-500 to-purple-600 text-white rounded-lg hover:from-purple-600 hover:to-purple-700 transition-all shadow-md hover:shadow-lg'
                >
                  <Download className='w-4 h-4' />
                  <span className='text-sm font-medium'>Download PDF</span>
                </button>
              )}
            </div>
            {
              !content ? (
                <div className='flex-1 flex justify-center items-center'>
                  <div className='text-sm flex flex-col items-center gap-5 text-gray-400'>
                    <Hash className='w-9 h-9' />
                    <p>Enter a topic and click “Generated title” to get started</p>
                  </div>
                </div>
              ) : (
                <div className='mt-3 flex-1 overflow-y-auto text-sm text-slate-700 leading-relaxed'>
                  <div className='prose max-w-none'>
                    <Markdown>{content}</Markdown>
                  </div>
                </div>
              )
            }
        </div>
      </div>
    </div>
  )
}

export default BlogTitles
