import React from 'react';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

const TermsAndConditions = () => {
    return (
        <div className="min-h-screen bg-white">
            <Navbar />
            <div className="max-w-4xl mx-auto px-6 py-20">
                <h1 className="text-4xl font-bold text-gray-900 mb-8 border-b pb-4">Terms and Conditions</h1>

                <div className="prose prose-orange max-w-none text-gray-700 space-y-6">
                    <section>
                        <h2 className="text-2xl font-semibold text-gray-800 mb-3">1. Acceptance of Terms</h2>
                        <p>By accessing and using Aivora AI, you agree to be bound by these Terms and Conditions and all applicable laws and regulations.</p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold text-gray-800 mb-3">2. Description of Service</h2>
                        <p>Aivora AI provides AI-powered content generation tools, including image generation, text processing, and resume review services. We reserve the right to modify or discontinue any aspect of the service at any time.</p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold text-gray-800 mb-3">3. User Accounts</h2>
                        <p>Users are responsible for maintaining the confidentiality of their account credentials and for all activities that occur under their account. You must notify us immediately of any unauthorized use.</p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold text-gray-800 mb-3">4. Intellectual Property</h2>
                        <p>While users retain ownership of the input provided to our AI tools, the underlying technology, platform, and interface are the property of Aivora AI. Output generated by the AI is subject to the specific licensing terms of the underlying AI models (e.g., OpenAI, Anthropic, Razorpay).</p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold text-gray-800 mb-3">5. Prohibited Conduct</h2>
                        <p>You agree not to use the service for any unlawful purposes, including generating harmful, offensive, or infringing content.</p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-semibold text-gray-800 mb-3">6. Limitation of Liability</h2>
                        <p>Aivora AI is provided "as is" without warranties of any kind. We shall not be liable for any indirect, incidental, or consequential damages resulting from the use of our service.</p>
                    </section>

                    <section className="mt-10 pt-6 border-t">
                        <p className="text-sm text-gray-500">Last updated: December 28, 2025</p>
                    </section>
                </div>
            </div>
            <Footer />
        </div>
    );
};

export default TermsAndConditions;
